var searchData=
[
  ['imbitarray_0',['ImBitArray',['../structImBitArray.html',1,'']]],
  ['imbitarray_3c_20imguikey_5fnamedkey_5fcount_2c_20_2dimguikey_5fnamedkey_5fbegin_20_3e_1',['ImBitArray&lt; ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN &gt;',['../structImBitArray.html',1,'']]],
  ['imbitvector_2',['ImBitVector',['../structImBitVector.html',1,'']]],
  ['imchunkstream_3',['ImChunkStream',['../structImChunkStream.html',1,'']]],
  ['imchunkstream_3c_20imguitablesettings_20_3e_4',['ImChunkStream&lt; ImGuiTableSettings &gt;',['../structImChunkStream.html',1,'']]],
  ['imchunkstream_3c_20imguiwindowsettings_20_3e_5',['ImChunkStream&lt; ImGuiWindowSettings &gt;',['../structImChunkStream.html',1,'']]],
  ['imcolor_6',['ImColor',['../structImColor.html',1,'']]],
  ['imdrawchannel_7',['ImDrawChannel',['../structImDrawChannel.html',1,'']]],
  ['imdrawcmd_8',['ImDrawCmd',['../structImDrawCmd.html',1,'']]],
  ['imdrawcmdheader_9',['ImDrawCmdHeader',['../structImDrawCmdHeader.html',1,'']]],
  ['imdrawdata_10',['ImDrawData',['../structImDrawData.html',1,'']]],
  ['imdrawdatabuilder_11',['ImDrawDataBuilder',['../structImDrawDataBuilder.html',1,'']]],
  ['imdrawlist_12',['ImDrawList',['../structImDrawList.html',1,'']]],
  ['imdrawlistshareddata_13',['ImDrawListSharedData',['../structImDrawListSharedData.html',1,'']]],
  ['imdrawlistsplitter_14',['ImDrawListSplitter',['../structImDrawListSplitter.html',1,'']]],
  ['imdrawvert_15',['ImDrawVert',['../structImDrawVert.html',1,'']]],
  ['imdrawvertallegro_16',['ImDrawVertAllegro',['../structImDrawVertAllegro.html',1,'']]],
  ['imfont_17',['ImFont',['../structImFont.html',1,'']]],
  ['imfontatlas_18',['ImFontAtlas',['../structImFontAtlas.html',1,'']]],
  ['imfontatlasbuilder_19',['ImFontAtlasBuilder',['../structImFontAtlasBuilder.html',1,'']]],
  ['imfontatlaspostprocessdata_20',['ImFontAtlasPostProcessData',['../structImFontAtlasPostProcessData.html',1,'']]],
  ['imfontatlasrect_21',['ImFontAtlasRect',['../structImFontAtlasRect.html',1,'']]],
  ['imfontatlasrectentry_22',['ImFontAtlasRectEntry',['../structImFontAtlasRectEntry.html',1,'']]],
  ['imfontbaked_23',['ImFontBaked',['../structImFontBaked.html',1,'']]],
  ['imfontconfig_24',['ImFontConfig',['../structImFontConfig.html',1,'']]],
  ['imfontglyph_25',['ImFontGlyph',['../structImFontGlyph.html',1,'']]],
  ['imfontglyphrangesbuilder_26',['ImFontGlyphRangesBuilder',['../structImFontGlyphRangesBuilder.html',1,'']]],
  ['imfontloader_27',['ImFontLoader',['../structImFontLoader.html',1,'']]],
  ['imfontstackdata_28',['ImFontStackData',['../structImFontStackData.html',1,'']]],
  ['imgl3wprocs_29',['ImGL3WProcs',['../unionImGL3WProcs.html',1,'']]],
  ['imgui_5fimplallegro5_5fdata_30',['ImGui_ImplAllegro5_Data',['../structImGui__ImplAllegro5__Data.html',1,'']]],
  ['imgui_5fimpldx10_5fdata_31',['ImGui_ImplDX10_Data',['../structImGui__ImplDX10__Data.html',1,'']]],
  ['imgui_5fimpldx10_5frenderstate_32',['ImGui_ImplDX10_RenderState',['../structImGui__ImplDX10__RenderState.html',1,'']]],
  ['imgui_5fimpldx10_5ftexture_33',['ImGui_ImplDX10_Texture',['../structImGui__ImplDX10__Texture.html',1,'']]],
  ['imgui_5fimpldx11_5fdata_34',['ImGui_ImplDX11_Data',['../structImGui__ImplDX11__Data.html',1,'']]],
  ['imgui_5fimpldx11_5frenderstate_35',['ImGui_ImplDX11_RenderState',['../structImGui__ImplDX11__RenderState.html',1,'']]],
  ['imgui_5fimpldx11_5ftexture_36',['ImGui_ImplDX11_Texture',['../structImGui__ImplDX11__Texture.html',1,'']]],
  ['imgui_5fimpldx12_5fdata_37',['ImGui_ImplDX12_Data',['../structImGui__ImplDX12__Data.html',1,'']]],
  ['imgui_5fimpldx12_5finitinfo_38',['ImGui_ImplDX12_InitInfo',['../structImGui__ImplDX12__InitInfo.html',1,'']]],
  ['imgui_5fimpldx12_5frenderbuffers_39',['ImGui_ImplDX12_RenderBuffers',['../structImGui__ImplDX12__RenderBuffers.html',1,'']]],
  ['imgui_5fimpldx12_5frenderstate_40',['ImGui_ImplDX12_RenderState',['../structImGui__ImplDX12__RenderState.html',1,'']]],
  ['imgui_5fimpldx12_5ftexture_41',['ImGui_ImplDX12_Texture',['../structImGui__ImplDX12__Texture.html',1,'']]],
  ['imgui_5fimpldx9_5fdata_42',['ImGui_ImplDX9_Data',['../structImGui__ImplDX9__Data.html',1,'']]],
  ['imgui_5fimplfreetype_5fdata_43',['ImGui_ImplFreeType_Data',['../structImGui__ImplFreeType__Data.html',1,'']]],
  ['imgui_5fimplfreetype_5ffontsrcbakeddata_44',['ImGui_ImplFreeType_FontSrcBakedData',['../structImGui__ImplFreeType__FontSrcBakedData.html',1,'']]],
  ['imgui_5fimplfreetype_5ffontsrcdata_45',['ImGui_ImplFreeType_FontSrcData',['../structImGui__ImplFreeType__FontSrcData.html',1,'']]],
  ['imgui_5fimplglfw_5fdata_46',['ImGui_ImplGlfw_Data',['../structImGui__ImplGlfw__Data.html',1,'']]],
  ['imgui_5fimplglfw_5fwindowtocontext_47',['ImGui_ImplGlfw_WindowToContext',['../structImGui__ImplGlfw__WindowToContext.html',1,'']]],
  ['imgui_5fimplmetal_5fdata_48',['ImGui_ImplMetal_Data',['../structImGui__ImplMetal__Data.html',1,'']]],
  ['imgui_5fimplopengl2_5fdata_49',['ImGui_ImplOpenGL2_Data',['../structImGui__ImplOpenGL2__Data.html',1,'']]],
  ['imgui_5fimplopengl3_5fdata_50',['ImGui_ImplOpenGL3_Data',['../structImGui__ImplOpenGL3__Data.html',1,'']]],
  ['imgui_5fimplosx_5fdata_51',['ImGui_ImplOSX_Data',['../structImGui__ImplOSX__Data.html',1,'']]],
  ['imgui_5fimplsdl2_5fdata_52',['ImGui_ImplSDL2_Data',['../structImGui__ImplSDL2__Data.html',1,'']]],
  ['imgui_5fimplsdl3_5fdata_53',['ImGui_ImplSDL3_Data',['../structImGui__ImplSDL3__Data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fdata_54',['ImGui_ImplSDLGPU3_Data',['../structImGui__ImplSDLGPU3__Data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fframedata_55',['ImGui_ImplSDLGPU3_FrameData',['../structImGui__ImplSDLGPU3__FrameData.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5finitinfo_56',['ImGui_ImplSDLGPU3_InitInfo',['../structImGui__ImplSDLGPU3__InitInfo.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5frenderstate_57',['ImGui_ImplSDLGPU3_RenderState',['../structImGui__ImplSDLGPU3__RenderState.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5fdata_58',['ImGui_ImplSDLRenderer2_Data',['../structImGui__ImplSDLRenderer2__Data.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5frenderstate_59',['ImGui_ImplSDLRenderer2_RenderState',['../structImGui__ImplSDLRenderer2__RenderState.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5fdata_60',['ImGui_ImplSDLRenderer3_Data',['../structImGui__ImplSDLRenderer3__Data.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5frenderstate_61',['ImGui_ImplSDLRenderer3_RenderState',['../structImGui__ImplSDLRenderer3__RenderState.html',1,'']]],
  ['imgui_5fimplstbtruetype_5ffontsrcdata_62',['ImGui_ImplStbTrueType_FontSrcData',['../structImGui__ImplStbTrueType__FontSrcData.html',1,'']]],
  ['imgui_5fimplvulkan_5fdata_63',['ImGui_ImplVulkan_Data',['../structImGui__ImplVulkan__Data.html',1,'']]],
  ['imgui_5fimplvulkan_5fframerenderbuffers_64',['ImGui_ImplVulkan_FrameRenderBuffers',['../structImGui__ImplVulkan__FrameRenderBuffers.html',1,'']]],
  ['imgui_5fimplvulkan_5finitinfo_65',['ImGui_ImplVulkan_InitInfo',['../structImGui__ImplVulkan__InitInfo.html',1,'']]],
  ['imgui_5fimplvulkan_5fpipelineinfo_66',['ImGui_ImplVulkan_PipelineInfo',['../structImGui__ImplVulkan__PipelineInfo.html',1,'']]],
  ['imgui_5fimplvulkan_5frenderstate_67',['ImGui_ImplVulkan_RenderState',['../structImGui__ImplVulkan__RenderState.html',1,'']]],
  ['imgui_5fimplvulkan_5ftexture_68',['ImGui_ImplVulkan_Texture',['../structImGui__ImplVulkan__Texture.html',1,'']]],
  ['imgui_5fimplvulkan_5fwindowrenderbuffers_69',['ImGui_ImplVulkan_WindowRenderBuffers',['../structImGui__ImplVulkan__WindowRenderBuffers.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframe_70',['ImGui_ImplVulkanH_Frame',['../structImGui__ImplVulkanH__Frame.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframesemaphores_71',['ImGui_ImplVulkanH_FrameSemaphores',['../structImGui__ImplVulkanH__FrameSemaphores.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindow_72',['ImGui_ImplVulkanH_Window',['../structImGui__ImplVulkanH__Window.html',1,'']]],
  ['imgui_5fimplwgpu_5fcreatesurfaceinfo_73',['ImGui_ImplWGPU_CreateSurfaceInfo',['../structImGui__ImplWGPU__CreateSurfaceInfo.html',1,'']]],
  ['imgui_5fimplwgpu_5fdata_74',['ImGui_ImplWGPU_Data',['../structImGui__ImplWGPU__Data.html',1,'']]],
  ['imgui_5fimplwgpu_5finitinfo_75',['ImGui_ImplWGPU_InitInfo',['../structImGui__ImplWGPU__InitInfo.html',1,'']]],
  ['imgui_5fimplwgpu_5frenderstate_76',['ImGui_ImplWGPU_RenderState',['../structImGui__ImplWGPU__RenderState.html',1,'']]],
  ['imgui_5fimplwgpu_5ftexture_77',['ImGui_ImplWGPU_Texture',['../structImGui__ImplWGPU__Texture.html',1,'']]],
  ['imgui_5fimplwin32_5fdata_78',['ImGui_ImplWin32_Data',['../structImGui__ImplWin32__Data.html',1,'']]],
  ['imguiboxselectstate_79',['ImGuiBoxSelectState',['../structImGuiBoxSelectState.html',1,'']]],
  ['imguicolormod_80',['ImGuiColorMod',['../structImGuiColorMod.html',1,'']]],
  ['imguicombopreviewdata_81',['ImGuiComboPreviewData',['../structImGuiComboPreviewData.html',1,'']]],
  ['imguicontext_82',['ImGuiContext',['../structImGuiContext.html',1,'']]],
  ['imguicontexthook_83',['ImGuiContextHook',['../structImGuiContextHook.html',1,'']]],
  ['imguidatatypeinfo_84',['ImGuiDataTypeInfo',['../structImGuiDataTypeInfo.html',1,'']]],
  ['imguidatatypestorage_85',['ImGuiDataTypeStorage',['../structImGuiDataTypeStorage.html',1,'']]],
  ['imguideactivateditemdata_86',['ImGuiDeactivatedItemData',['../structImGuiDeactivatedItemData.html',1,'']]],
  ['imguidebugallocentry_87',['ImGuiDebugAllocEntry',['../structImGuiDebugAllocEntry.html',1,'']]],
  ['imguidebugallocinfo_88',['ImGuiDebugAllocInfo',['../structImGuiDebugAllocInfo.html',1,'']]],
  ['imguidebugitempathquery_89',['ImGuiDebugItemPathQuery',['../structImGuiDebugItemPathQuery.html',1,'']]],
  ['imguidemowindowdata_90',['ImGuiDemoWindowData',['../structImGuiDemoWindowData.html',1,'']]],
  ['imguierrorrecoverystate_91',['ImGuiErrorRecoveryState',['../structImGuiErrorRecoveryState.html',1,'']]],
  ['imguifocusscopedata_92',['ImGuiFocusScopeData',['../structImGuiFocusScopeData.html',1,'']]],
  ['imguigetnamefromindexoldtonewcallbackdata_93',['ImGuiGetNameFromIndexOldToNewCallbackData',['../structImGuiGetNameFromIndexOldToNewCallbackData.html',1,'']]],
  ['imguigroupdata_94',['ImGuiGroupData',['../structImGuiGroupData.html',1,'']]],
  ['imguiidstacktool_95',['ImGuiIDStackTool',['../structImGuiIDStackTool.html',1,'']]],
  ['imguiinputevent_96',['ImGuiInputEvent',['../structImGuiInputEvent.html',1,'']]],
  ['imguiinputeventappfocused_97',['ImGuiInputEventAppFocused',['../structImGuiInputEventAppFocused.html',1,'']]],
  ['imguiinputeventkey_98',['ImGuiInputEventKey',['../structImGuiInputEventKey.html',1,'']]],
  ['imguiinputeventmousebutton_99',['ImGuiInputEventMouseButton',['../structImGuiInputEventMouseButton.html',1,'']]],
  ['imguiinputeventmousepos_100',['ImGuiInputEventMousePos',['../structImGuiInputEventMousePos.html',1,'']]],
  ['imguiinputeventmousewheel_101',['ImGuiInputEventMouseWheel',['../structImGuiInputEventMouseWheel.html',1,'']]],
  ['imguiinputeventtext_102',['ImGuiInputEventText',['../structImGuiInputEventText.html',1,'']]],
  ['imguiinputtextcallbackdata_103',['ImGuiInputTextCallbackData',['../structImGuiInputTextCallbackData.html',1,'']]],
  ['imguiinputtextdeactivatedstate_104',['ImGuiInputTextDeactivatedState',['../structImGuiInputTextDeactivatedState.html',1,'']]],
  ['imguiinputtextstate_105',['ImGuiInputTextState',['../structImGuiInputTextState.html',1,'']]],
  ['imguiio_106',['ImGuiIO',['../structImGuiIO.html',1,'']]],
  ['imguikeydata_107',['ImGuiKeyData',['../structImGuiKeyData.html',1,'']]],
  ['imguikeyownerdata_108',['ImGuiKeyOwnerData',['../structImGuiKeyOwnerData.html',1,'']]],
  ['imguikeyroutingdata_109',['ImGuiKeyRoutingData',['../structImGuiKeyRoutingData.html',1,'']]],
  ['imguikeyroutingtable_110',['ImGuiKeyRoutingTable',['../structImGuiKeyRoutingTable.html',1,'']]],
  ['imguilastitemdata_111',['ImGuiLastItemData',['../structImGuiLastItemData.html',1,'']]],
  ['imguilistclipper_112',['ImGuiListClipper',['../structImGuiListClipper.html',1,'']]],
  ['imguilistclipperdata_113',['ImGuiListClipperData',['../structImGuiListClipperData.html',1,'']]],
  ['imguilistclipperrange_114',['ImGuiListClipperRange',['../structImGuiListClipperRange.html',1,'']]],
  ['imguilocentry_115',['ImGuiLocEntry',['../structImGuiLocEntry.html',1,'']]],
  ['imguimenucolumns_116',['ImGuiMenuColumns',['../structImGuiMenuColumns.html',1,'']]],
  ['imguimetricsconfig_117',['ImGuiMetricsConfig',['../structImGuiMetricsConfig.html',1,'']]],
  ['imguimultiselectio_118',['ImGuiMultiSelectIO',['../structImGuiMultiSelectIO.html',1,'']]],
  ['imguimultiselectstate_119',['ImGuiMultiSelectState',['../structImGuiMultiSelectState.html',1,'']]],
  ['imguimultiselecttempdata_120',['ImGuiMultiSelectTempData',['../structImGuiMultiSelectTempData.html',1,'']]],
  ['imguinavitemdata_121',['ImGuiNavItemData',['../structImGuiNavItemData.html',1,'']]],
  ['imguinextitemdata_122',['ImGuiNextItemData',['../structImGuiNextItemData.html',1,'']]],
  ['imguinextwindowdata_123',['ImGuiNextWindowData',['../structImGuiNextWindowData.html',1,'']]],
  ['imguiobserver_124',['ImGuiObserver',['../interfaceImGuiObserver.html',1,'']]],
  ['imguioldcolumndata_125',['ImGuiOldColumnData',['../structImGuiOldColumnData.html',1,'']]],
  ['imguioldcolumns_126',['ImGuiOldColumns',['../structImGuiOldColumns.html',1,'']]],
  ['imguionceuponaframe_127',['ImGuiOnceUponAFrame',['../structImGuiOnceUponAFrame.html',1,'']]],
  ['imguipayload_128',['ImGuiPayload',['../structImGuiPayload.html',1,'']]],
  ['imguiplatformimedata_129',['ImGuiPlatformImeData',['../structImGuiPlatformImeData.html',1,'']]],
  ['imguiplatformio_130',['ImGuiPlatformIO',['../structImGuiPlatformIO.html',1,'']]],
  ['imguiplotarraygetterdata_131',['ImGuiPlotArrayGetterData',['../structImGuiPlotArrayGetterData.html',1,'']]],
  ['imguipopupdata_132',['ImGuiPopupData',['../structImGuiPopupData.html',1,'']]],
  ['imguiptrorindex_133',['ImGuiPtrOrIndex',['../structImGuiPtrOrIndex.html',1,'']]],
  ['imguiresizeborderdef_134',['ImGuiResizeBorderDef',['../structImGuiResizeBorderDef.html',1,'']]],
  ['imguiresizegripdef_135',['ImGuiResizeGripDef',['../structImGuiResizeGripDef.html',1,'']]],
  ['imguiselectionbasicstorage_136',['ImGuiSelectionBasicStorage',['../structImGuiSelectionBasicStorage.html',1,'']]],
  ['imguiselectionexternalstorage_137',['ImGuiSelectionExternalStorage',['../structImGuiSelectionExternalStorage.html',1,'']]],
  ['imguiselectionrequest_138',['ImGuiSelectionRequest',['../structImGuiSelectionRequest.html',1,'']]],
  ['imguisettingshandler_139',['ImGuiSettingsHandler',['../structImGuiSettingsHandler.html',1,'']]],
  ['imguishrinkwidthitem_140',['ImGuiShrinkWidthItem',['../structImGuiShrinkWidthItem.html',1,'']]],
  ['imguisizecallbackdata_141',['ImGuiSizeCallbackData',['../structImGuiSizeCallbackData.html',1,'']]],
  ['imguistacklevelinfo_142',['ImGuiStackLevelInfo',['../structImGuiStackLevelInfo.html',1,'']]],
  ['imguistorage_143',['ImGuiStorage',['../structImGuiStorage.html',1,'']]],
  ['imguistoragepair_144',['ImGuiStoragePair',['../structImGuiStoragePair.html',1,'']]],
  ['imguistyle_145',['ImGuiStyle',['../structImGuiStyle.html',1,'']]],
  ['imguistylemod_146',['ImGuiStyleMod',['../structImGuiStyleMod.html',1,'']]],
  ['imguistylevarinfo_147',['ImGuiStyleVarInfo',['../structImGuiStyleVarInfo.html',1,'']]],
  ['imguitabbar_148',['ImGuiTabBar',['../structImGuiTabBar.html',1,'']]],
  ['imguitabbarsection_149',['ImGuiTabBarSection',['../structImGuiTabBarSection.html',1,'']]],
  ['imguitabitem_150',['ImGuiTabItem',['../structImGuiTabItem.html',1,'']]],
  ['imguitable_151',['ImGuiTable',['../structImGuiTable.html',1,'']]],
  ['imguitablecelldata_152',['ImGuiTableCellData',['../structImGuiTableCellData.html',1,'']]],
  ['imguitablecolumn_153',['ImGuiTableColumn',['../structImGuiTableColumn.html',1,'']]],
  ['imguitablecolumnsettings_154',['ImGuiTableColumnSettings',['../structImGuiTableColumnSettings.html',1,'']]],
  ['imguitablecolumnsortspecs_155',['ImGuiTableColumnSortSpecs',['../structImGuiTableColumnSortSpecs.html',1,'']]],
  ['imguitablefixdisplayordercolumndata_156',['ImGuiTableFixDisplayOrderColumnData',['../structImGuiTableFixDisplayOrderColumnData.html',1,'']]],
  ['imguitableheaderdata_157',['ImGuiTableHeaderData',['../structImGuiTableHeaderData.html',1,'']]],
  ['imguitableinstancedata_158',['ImGuiTableInstanceData',['../structImGuiTableInstanceData.html',1,'']]],
  ['imguitablesettings_159',['ImGuiTableSettings',['../structImGuiTableSettings.html',1,'']]],
  ['imguitablesortspecs_160',['ImGuiTableSortSpecs',['../structImGuiTableSortSpecs.html',1,'']]],
  ['imguitabletempdata_161',['ImGuiTableTempData',['../structImGuiTableTempData.html',1,'']]],
  ['imguitextbuffer_162',['ImGuiTextBuffer',['../structImGuiTextBuffer.html',1,'']]],
  ['imguitextfilter_163',['ImGuiTextFilter',['../structImGuiTextFilter.html',1,'']]],
  ['imguitextindex_164',['ImGuiTextIndex',['../structImGuiTextIndex.html',1,'']]],
  ['imguitextrange_165',['ImGuiTextRange',['../structImGuiTextFilter_1_1ImGuiTextRange.html',1,'ImGuiTextFilter']]],
  ['imguitreenodestackdata_166',['ImGuiTreeNodeStackData',['../structImGuiTreeNodeStackData.html',1,'']]],
  ['imguitypingselectrequest_167',['ImGuiTypingSelectRequest',['../structImGuiTypingSelectRequest.html',1,'']]],
  ['imguitypingselectstate_168',['ImGuiTypingSelectState',['../structImGuiTypingSelectState.html',1,'']]],
  ['imguiviewport_169',['ImGuiViewport',['../structImGuiViewport.html',1,'']]],
  ['imguiviewportp_170',['ImGuiViewportP',['../structImGuiViewportP.html',1,'']]],
  ['imguiwindow_171',['ImGuiWindow',['../structImGuiWindow.html',1,'']]],
  ['imguiwindowsettings_172',['ImGuiWindowSettings',['../structImGuiWindowSettings.html',1,'']]],
  ['imguiwindowstackdata_173',['ImGuiWindowStackData',['../structImGuiWindowStackData.html',1,'']]],
  ['imguiwindowsummary_174',['ImGuiWindowSummary',['../classimgui__lldb_1_1ImGuiWindowSummary.html',1,'imgui_lldb']]],
  ['imguiwindowtempdata_175',['ImGuiWindowTempData',['../structImGuiWindowTempData.html',1,'']]],
  ['imnewwrapper_176',['ImNewWrapper',['../structImNewWrapper.html',1,'']]],
  ['impool_177',['ImPool',['../structImPool.html',1,'']]],
  ['impool_3c_20imguimultiselectstate_20_3e_178',['ImPool&lt; ImGuiMultiSelectState &gt;',['../structImPool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_179',['ImPool&lt; ImGuiTabBar &gt;',['../structImPool.html',1,'']]],
  ['impool_3c_20imguitable_20_3e_180',['ImPool&lt; ImGuiTable &gt;',['../structImPool.html',1,'']]],
  ['imrect_181',['ImRect',['../structImRect.html',1,'']]],
  ['imrectsummary_182',['ImRectSummary',['../classimgui__lldb_1_1ImRectSummary.html',1,'imgui_lldb']]],
  ['imspan_183',['ImSpan',['../structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecelldata_20_3e_184',['ImSpan&lt; ImGuiTableCellData &gt;',['../structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecolumn_20_3e_185',['ImSpan&lt; ImGuiTableColumn &gt;',['../structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecolumnidx_20_3e_186',['ImSpan&lt; ImGuiTableColumnIdx &gt;',['../structImSpan.html',1,'']]],
  ['imspanallocator_187',['ImSpanAllocator',['../structImSpanAllocator.html',1,'']]],
  ['imspansynth_188',['ImSpanSynth',['../classimgui__lldb_1_1ImSpanSynth.html',1,'imgui_lldb']]],
  ['imstablevector_189',['ImStableVector',['../structImStableVector.html',1,'']]],
  ['imstablevector_3c_20imfontbaked_2c_2032_20_3e_190',['ImStableVector&lt; ImFontBaked, 32 &gt;',['../structImStableVector.html',1,'']]],
  ['imtexturedata_191',['ImTextureData',['../structImTextureData.html',1,'']]],
  ['imtexturerect_192',['ImTextureRect',['../structImTextureRect.html',1,'']]],
  ['imtextureref_193',['ImTextureRef',['../structImTextureRef.html',1,'']]],
  ['imtriangulator_194',['ImTriangulator',['../structImTriangulator.html',1,'']]],
  ['imtriangulatornode_195',['ImTriangulatorNode',['../structImTriangulatorNode.html',1,'']]],
  ['imtriangulatornodespan_196',['ImTriangulatorNodeSpan',['../structImTriangulatorNodeSpan.html',1,'']]],
  ['imvec1_197',['ImVec1',['../structImVec1.html',1,'']]],
  ['imvec2_198',['ImVec2',['../structImVec2.html',1,'']]],
  ['imvec2i_199',['ImVec2i',['../structImVec2i.html',1,'']]],
  ['imvec2ih_200',['ImVec2ih',['../structImVec2ih.html',1,'']]],
  ['imvec4_201',['ImVec4',['../structImVec4.html',1,'']]],
  ['imvector_202',['ImVector',['../structImVector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_203',['ImVector&lt; char * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20char_20_3e_204',['ImVector&lt; char &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_205',['ImVector&lt; const char * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20exampleasset_20_3e_206',['ImVector&lt; ExampleAsset &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20exampletreenode_20_2a_20_3e_207',['ImVector&lt; ExampleTreeNode * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20float_20_3e_208',['ImVector&lt; float &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_209',['ImVector&lt; ImDrawChannel &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_210',['ImVector&lt; ImDrawCmd &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_211',['ImVector&lt; ImDrawIdx &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_212',['ImVector&lt; ImDrawList * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawlistshareddata_20_2a_20_3e_213',['ImVector&lt; ImDrawListSharedData * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_214',['ImVector&lt; ImDrawVert &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imdrawvertallegro_20_3e_215',['ImVector&lt; ImDrawVertAllegro &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_216',['ImVector&lt; ImFont * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontatlas_20_2a_20_3e_217',['ImVector&lt; ImFontAtlas * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontatlasrectentry_20_3e_218',['ImVector&lt; ImFontAtlasRectEntry &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontbaked_20_2a_20_3e_219',['ImVector&lt; ImFontBaked * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_2a_20_3e_220',['ImVector&lt; ImFontConfig * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_221',['ImVector&lt; ImFontConfig &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_222',['ImVector&lt; ImFontGlyph &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imfontstackdata_20_3e_223',['ImVector&lt; ImFontStackData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkan_5fframerenderbuffers_20_3e_224',['ImVector&lt; ImGui_ImplVulkan_FrameRenderBuffers &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframe_20_3e_225',['ImVector&lt; ImGui_ImplVulkanH_Frame &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframesemaphores_20_3e_226',['ImVector&lt; ImGui_ImplVulkanH_FrameSemaphores &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_227',['ImVector&lt; ImGuiColorMod &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguicontexthook_20_3e_228',['ImVector&lt; ImGuiContextHook &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguifocusscopedata_20_3e_229',['ImVector&lt; ImGuiFocusScopeData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_230',['ImVector&lt; ImGuiGroupData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_231',['ImVector&lt; ImGuiID &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiinputevent_20_3e_232',['ImVector&lt; ImGuiInputEvent &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_233',['ImVector&lt; ImGuiItemFlags &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguikeyroutingdata_20_3e_234',['ImVector&lt; ImGuiKeyRoutingData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguilistclipperdata_20_3e_235',['ImVector&lt; ImGuiListClipperData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguilistclipperrange_20_3e_236',['ImVector&lt; ImGuiListClipperRange &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguimultiselectstate_20_3e_237',['ImVector&lt; ImGuiMultiSelectState &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguimultiselecttempdata_20_3e_238',['ImVector&lt; ImGuiMultiSelectTempData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguioldcolumndata_20_3e_239',['ImVector&lt; ImGuiOldColumnData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguioldcolumns_20_3e_240',['ImVector&lt; ImGuiOldColumns &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_241',['ImVector&lt; ImGuiPopupData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_242',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiselectionrequest_20_3e_243',['ImVector&lt; ImGuiSelectionRequest &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_244',['ImVector&lt; ImGuiSettingsHandler &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_245',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguistacklevelinfo_20_3e_246',['ImVector&lt; ImGuiStackLevelInfo &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguistoragepair_20_3e_247',['ImVector&lt; ImGuiStoragePair &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_248',['ImVector&lt; ImGuiStyleMod &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_249',['ImVector&lt; ImGuiTabBar &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_250',['ImVector&lt; ImGuiTabItem &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitable_20_3e_251',['ImVector&lt; ImGuiTable &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitablecolumnsortspecs_20_3e_252',['ImVector&lt; ImGuiTableColumnSortSpecs &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitableheaderdata_20_3e_253',['ImVector&lt; ImGuiTableHeaderData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitableinstancedata_20_3e_254',['ImVector&lt; ImGuiTableInstanceData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitabletempdata_20_3e_255',['ImVector&lt; ImGuiTableTempData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_256',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguitreenodestackdata_20_3e_257',['ImVector&lt; ImGuiTreeNodeStackData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiviewportp_20_2a_20_3e_258',['ImVector&lt; ImGuiViewportP * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_259',['ImVector&lt; ImGuiWindow * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imguiwindowstackdata_20_3e_260',['ImVector&lt; ImGuiWindowStackData &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imtexturedata_20_2a_20_3e_261',['ImVector&lt; ImTextureData * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imtexturerect_20_3e_262',['ImVector&lt; ImTextureRect &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imtextureref_20_3e_263',['ImVector&lt; ImTextureRef &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imu16_20_3e_264',['ImVector&lt; ImU16 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_265',['ImVector&lt; ImU32 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imu8_20_3e_266',['ImVector&lt; ImU8 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_267',['ImVector&lt; ImVec2 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_268',['ImVector&lt; ImVec4 &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_269',['ImVector&lt; ImWchar &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20int_20_3e_270',['ImVector&lt; int &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20mydocument_20_2a_20_3e_271',['ImVector&lt; MyDocument * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_272',['ImVector&lt; MyDocument &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5ffcolor_20_3e_273',['ImVector&lt; SDL_FColor &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamecontroller_20_2a_20_3e_274',['ImVector&lt; SDL_GameController * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamepad_20_2a_20_3e_275',['ImVector&lt; SDL_Gamepad * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20stbrp_5fnode_20_3e_276',['ImVector&lt; stbrp_node &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20t_20_2a_20_3e_277',['ImVector&lt; T * &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_278',['ImVector&lt; unsigned char &gt;',['../structImVector.html',1,'']]],
  ['imvector_3c_20vkformat_20_3e_279',['ImVector&lt; VkFormat &gt;',['../structImVector.html',1,'']]],
  ['imvectorsynth_280',['ImVectorSynth',['../classimgui__lldb_1_1ImVectorSynth.html',1,'imgui_lldb']]],
  ['inputtextcallback_5fuserdata_281',['InputTextCallback_UserData',['../structInputTextCallback__UserData.html',1,'']]]
];
